// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { ExamineeOrigin } from "./ExamineeOrigin";

export interface Examinee { id: EntityId, name: string, surenames: string, origin: ExamineeOrigin, court: number, }