// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExamineeOrigin } from "./ExamineeOrigin";

export interface ExamineeForCreate { name: string, surenames: string, origin: ExamineeOrigin, court_number: number, }